version: "3.8"
services:
  backend:
    container_name: backend
    ports:
      - "8000:8000"
    build: 
      context: ../Intership/backend
      dockerfile: Dockerfile

  frontend:
    container_name: frontend
    ports:
      - "5173:5173"
    build: 
      context: ../Intership/frontend/datn
      dockerfile: Dockerfile
